# Generated by Django 5.2.14 on 2026-05-27 07:40

import registry.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_user_role_default_staffaffiliation_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffaffiliation',
            name='start_date',
            field=models.DateField(default=registry.models.default_start_date),
        ),
    ]
