# Generated by Django 5.2.14 on 2026-05-27 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_alter_staffaffiliation_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuschangelog',
            name='accountability_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='statuschangelog',
            name='accountability_statement',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='RegistryDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('practitioner_license', 'Practitioner license'), ('professional_indemnity', 'Professional indemnity'), ('cpd_certificate', 'CPD certificate'), ('facility_accreditation', 'Facility accreditation'), ('internship_certificate', 'Internship certificate'), ('other', 'Other supporting document')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('file', models.FileField(blank=True, upload_to='registry_documents/%Y/%m/')),
                ('review_status', models.CharField(choices=[('pending', 'Pending review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_on', models.DateField(blank=True, null=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.healthcarefacility')),
                ('practitioner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registry.practitionerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
