# Generated by Django 5.2.14 on 2026-05-28 08:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('registry', '0004_statuschangelog_accountability_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='healthcarefacility',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('registration_number'), name='uniq_facility_registration_number_ci'),
        ),
        migrations.AddConstraint(
            model_name='practitionerprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('license_number'), name='uniq_practitioner_license_number_ci'),
        ),
        migrations.AddConstraint(
            model_name='registrydocument',
            constraint=models.UniqueConstraint(fields=('practitioner', 'document_type', 'reference_number'), name='uniq_practitioner_document_record'),
        ),
        migrations.AddConstraint(
            model_name='registrydocument',
            constraint=models.UniqueConstraint(fields=('facility', 'document_type', 'reference_number'), name='uniq_facility_document_record'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('username'), name='uniq_user_username_ci'),
        ),
    ]
