# Generated by Django 5.2.14 on 2026-06-03 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='personal_physician',
            field=models.ForeignKey(blank=True, help_text="Hospital admin's linked personal physician for quick access.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hospital_admin_patients', to='registry.practitionerprofile'),
        ),
        migrations.CreateModel(
            name='FacilityApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_type', models.CharField(choices=[('licence_renewal', 'Facility licence renewal / application'), ('services_update', 'Update of services offered')], max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Pending regulator review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('facility_legal_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=32)),
                ('county', models.CharField(max_length=64)),
                ('physical_address', models.CharField(max_length=255)),
                ('postal_address', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=254)),
                ('director_name', models.CharField(max_length=255, verbose_name='Director of medical services')),
                ('bed_capacity', models.PositiveIntegerField(default=0)),
                ('services_requested', models.TextField(help_text='Services to be offered or updated')),
                ('accreditation_sought_until', models.DateField()),
                ('declaration_agreed', models.BooleanField(default=False)),
                ('supporting_file', models.FileField(blank=True, upload_to='facility_applications/%Y/%m/')),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='registry.healthcarefacility')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_facility_applications', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facility_applications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
