# Generated by Django 5.2.15 on 2026-06-09 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_user_personal_physician_facilityapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('regulator', 'Regulator (KMPDC)'), ('hospital_admin', 'Hospital Administrator'), ('practitioner', 'Medical Practitioner'), ('system_admin', 'System Administrator')], default='practitioner', max_length=20),
        ),
    ]
