# Generated by Django 5.2.14 on 2026-06-16 12:23

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_add_system_admin_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='PractitionerRenewalApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_employer', models.CharField(blank=True, max_length=255)),
                ('work_contact_phone', models.CharField(blank=True, max_length=32)),
                ('work_email', models.EmailField(blank=True, max_length=254)),
                ('has_practised_continuously', models.CharField(blank=True, max_length=8)),
                ('practice_break_reason', models.TextField(blank=True)),
                ('has_malpractice_history', models.CharField(blank=True, max_length=8)),
                ('malpractice_details', models.TextField(blank=True)),
                ('practitioner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renewal_applications', to='registry.practitionerprofile')),
            ],
            options={
                'verbose_name': 'Practitioner renewal application',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
