# Generated by Django 5.2.14 on 2026-07-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_facilityrenewalpayment_practitionerrenewalpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilityrenewalpayment',
            name='payment_type',
            field=models.CharField(choices=[('licence_renewal', 'Licence renewal'), ('services_update', 'Services update')], default='licence_renewal', max_length=32),
        ),
    ]
