# Generated by Django 5.2.14 on 2026-07-21 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_facilityrenewalpayment_payment_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='facilityapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('facility', 'application_type'), name='uniq_facility_pending_application_type'),
        ),
        migrations.AddConstraint(
            model_name='facilityrenewalpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'completed'])), fields=('facility', 'payment_type'), name='uniq_facility_active_payment_type'),
        ),
        migrations.AddConstraint(
            model_name='practitionerrenewalpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'completed'])), fields=('practitioner',), name='uniq_practitioner_active_payment'),
        ),
    ]
