# Generated by Django 5.2.14 on 2026-07-21 17:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_facilityapplication_uniq_facility_pending_application_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='practitionerrenewalapplication',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='practitionerrenewalapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='practitionerrenewalapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_practitioner_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='practitionerrenewalapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending regulator review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=16),
        ),
    ]
